Friend Module Nouns
    Friend ReadOnly ASSKEY As String = "ass-key"
    Friend ReadOnly BEGGAR As String = "beggar"
    Friend ReadOnly BIRD As String = "bird"
    Friend ReadOnly BOARD As String = "board"
    Friend ReadOnly BUSH As String = "bush"
    Friend ReadOnly BUTTHOLE As String = "butthole"
    Friend ReadOnly BUTTPLUG As String = "buttplug"
    Friend ReadOnly FLOOR As String = "floor"
    Friend ReadOnly GUARD As String = "guard"
    Friend ReadOnly KEY As String = "key"
    Friend ReadOnly KLART As String = "klart"
    Friend ReadOnly [ME] As String = "me"
    Friend ReadOnly MYSELF As String = "myself"
    Friend ReadOnly NOTE As String = "note"
    Friend ReadOnly SWALLOW As String = "swallow"
    Friend ReadOnly TABLE As String = "table"
    Friend ReadOnly SHIT As String = "shit"
    Friend ReadOnly SHRINE As String = "shrine"
    Friend ReadOnly STREAMBOO As String = "streamboo"
    Friend ReadOnly VENDOR As String = "vendor"
    Friend ReadOnly POSTING As String = "posting"
    Friend ReadOnly JOB As String = "job"
End Module

